### ISSUE TITLE
Use Config Vars For Token

### ISSUE THREAD

**Issue by RandomInventor** [OIVAS7572/lichess-bot#101]
It will be good if implement config vars for token otherwise others might able to see our **token**
thanks.

**Comment by OIVAS7572** [comment]
@RandomInventor 
You can submit your request to this repo. https://github.com/ShailChoksi/lichess-bot/issues this is the main repo of this repo

**Comment by RandomInventor** [comment]
@OIVAS7572 your repo is based on Docker in Heroku submitting request to https://github.com/ShailChoksi/lichess-bot/issues makes nothing for docker

**Comment by OIVAS7572** [comment]
I will consider it

**Comment by OIVAS7572** [comment]
But it need to done in python code to impliment with docker

**Comment by barca-cloud** [comment]
@OIVAS7572 no need of that this idea has been taken from the hyperbot and belive me it very weak so it ia uaeleass for that
@RandomInventor good idea but not from hyperbot

**Comment by OIVAS7572** [comment]
It is Difficult to Docker container to read env var from host Heroku. Anyway you need to edit onefile

**Comment by RandomInventor** [comment]
@barca-cloud no it will definitely not weaken the bot config vars are for hiding lichess bot token from others https://devcenter.heroku.com/articles/config-vars

**Comment by RandomInventor** [comment]
@OIVAS7572 I cannot work on this issue because I am not familiar with docker if I know I will send a pr

**Comment by RandomInventor** [comment]
@OIVAS7572 maybe in https://github.com/OIVAS7572/lichess-bot/blob/master/Dockerfile
