### ISSUE TITLE
bot not sending good luck at blitz or bullet or rapid but it gives in chess 960

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#108]
title.

**Comment by OIVAS7572** [comment]
wait for https://github.com/ShailChoksi/lichess-bot to merge

**Comment by barca-cloud** [comment]
@OIVAS7572  can you see thois https://github.com/barca-cloud/thechessbot/pull/8 in my reo and tell me if it good or not.

**Comment by OIVAS7572** [comment]
It is editable. Good

**Comment by barca-cloud** [comment]
Ok! I will merge the pr
