### ISSUE TITLE
i am not able to add any other engine , why is that happening?

### ISSUE THREAD

**Issue by lichess460** [OIVAS7572/lichess-bot#12]
`pls help`

**Comment by lichess460** [comment]
it says it doesn't have access or permissions

**Comment by TheYoBots** [comment]
Rename whatever engine you are using to `stockfishmodern` will definitely work. Changing the entire name of the engine requires changes in other places too and might get complicated for you so the easiest and best thing to do is simply rename whatever engine binary you have to `stockfishmodern`. Other than that make sure it is compatible with heroku and runs under to uci or xboard protocol.

**Comment by TheYoBots** [comment]
I’ve solved it for you. This can be closed now.

**Comment by OIVAS7572** [comment]
for this problem.yesterday I bring some updates to Dockerfile
please update docker file in your repo from my repo

**Comment by OIVAS7572** [comment]
OR I PROPOSED  YOU A PULL REQUEST ACCEPT THAT

**Comment by TheYoBots** [comment]
The updates you made yesterday was what gav the problem, so I’ve reverted that commit for him. Also this has been solved @OIVAS7572 so @lichess460 doesn’t need to merge your pr as that again results in the same issue.
