### ISSUE TITLE
Can you all please bring back engine folder?

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#120]
Pls can you bring it back itwill be more helpfull to change engines.

**Comment by OIVAS7572** [comment]
I will consider that.

You can create a new folder and add a line `COPY ./engine .` in Dockerfile (before the 6th line).
Don't make any changes to path in config.yml. But this help to you put engine binary in engine folder. and when deploying it will copy binary from `./engine` folder to `./`

Thank you

**Comment by thechipsss** [comment]
If this happens then it would be good

**Comment by OIVAS7572** [comment]
I think it is not necessary you can upload your engine directly

**Comment by OIVAS7572** [comment]
Click on Add file -> Upload file -> select file and commit. Then put your engine's name in ***config.yml*** and ***Dockerfile***
