### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Devil-commits** [OIVAS7572/lichess-bot#129]
Add a new polyglot book, Echidna.bin. Pretty good if compared to Drawkiller

http://www.mediafire.com/file/xldokbhtiosnjtp/EchidnaBINBOOK.7z/file
Book link

**Comment by Devil-commits** [comment]
Strong lichess bots like Resolute use this.

**Comment by TheYoBots** [comment]
Feel free to add any opening book you prefer in your own repository.

**Comment by OIVAS7572** [comment]
@Devil-commits 
We all ready using `Goi5.1.bin` book
