### ISSUE TITLE
Support Lc0

### ISSUE THREAD

**Issue by vibranium21** [OIVAS7572/lichess-bot#13]
correct me if i am wrong, but shouldnt there be an Lc0 file inside the engines file, Lc0 is a very popular engine that i am pretty sure is possible to use deployed via heroku fo a lichess bot

**Comment by OIVAS7572** [comment]
lc0 is mainly built for running on graphics card. Heroku has no graphics card

**Comment by OIVAS7572** [comment]
I didn't know about lc0 engine.
I don't have lc0 engine.
If any body have latest lc0 engine for linux that won't use graphics card.
Also corresponding to Stockfish SSE4.1 + POPCNT 's cpu architecture.
I can test it and publish.
Thanks you

**Comment by OIVAS7572** [comment]
@TheYoBots 
oh
I didn't saw your message. Please mention me in message in future.
I studied about Lc0 and compiled it in google cloud and committed binary and weight from google cloud.
What all other things needed to run Lc0 in Heroku

**Comment by OIVAS7572** [comment]
@TheYoBots 
.dll file is will not work in Linux (We are using Linux on Heroku Docker container)
.dll files are maded for Windows. I found [here](https://www.google.com/search?q=dll+file&oq=dll+file&aqs=chrome..69i57j0l4j0i10j0l4.20207j0j7&sourceid=chrome&ie=UTF-8)

**Comment by TheYoBots** [comment]
Then it should work without the .dll file I assume.

**Comment by TheYoBots** [comment]
@OIVAS7572 Maybe if you could create a new branch called Lc0 and there is will do some tests.

**Comment by OIVAS7572** [comment]
@TheYoBots 
Lc0 Don't need .dll . But it need a Library named `libopenblas-dev` For Running on CPU in Linux.
Yes that is a good idea to create a Branch. I will do it
Running Lc0 in Heroku is a funny thing. Because It made For running in GPU.
> Without a graphics card, using only my CPU, I barely get 20% the performance I get with the GPU (graphics processing unit).

I got this one From Old [Report](https://en.chessbase.com/post/leela-chess-zero-alphazero-for-the-pc)

Thanks

**Comment by OIVAS7572** [comment]
I created [Branch](https://github.com/OIVAS7572/lichess-bot/tree/Lc0)
What I want to do in config.yml ?
If anybody Have experience in using Lc0, Help me in configuring config.yml or create a pull request.
There is something Special in weights settings in config.yml.
I don't know best setting for config.yml

**Comment by vibranium21** [comment]
Lc0 will use whatever .pbgz file is in the engines folder and  the binary name of Lc0 is Lc0

**Comment by vibranium21** [comment]
also @OIVAS7572  there are a few settings for just lc0 and not other engines

**Comment by OIVAS7572** [comment]
@vibranium21 
yes, what is the problem in binary name.
I didn't made any changes in config.yml. I will change soon.

**Comment by TheYoBots** [comment]
I have completed the implementation in the `lczero` branch https://github.com/OIVAS7572/lichess-bot/tree/lczero . Do test and tell me whether it works. If it doesn’t work do send your error logs. Also the `Lc0` branch can be deleted now.

**Comment by TheYoBots** [comment]
I’ll close this since we have an lc0 branch now.

**Comment by OIVAS7572** [comment]
@TheYoBots 
Is it working
