### ISSUE TITLE
stockfish 15 also add matchmaking

### ISSUE THREAD

**Issue by thechipsss** [OIVAS7572/lichess-bot#142]
will you all upgrade to stockfish 15 and also dev? and yes will we ever get https://github.com/ShailChoksi/lichess-bot/pull/473#partial-pull-merging ? this here?

**Comment by thechipsss** [comment]
also @TheYoBots (sorry for he ping) does this work in windows 11?

**Comment by SriMethan** [comment]
Yes.

**Comment by TheYoBots** [comment]
Will push changes as soon as the matchmaking pr is merged.

**Comment by thechipsss** [comment]
all right thanks
