### ISSUE TITLE
Problem with installing heroku cli

### ISSUE THREAD

**Issue by CGP-Lichess** [OIVAS7572/lichess-bot#16]
@OIVAS7572 , I was trying to make  a bot running on Heroku for my friend. I even deployed and runned the commands on CMD , i already installed HEROKU CLI. But the Bot is not coming online. Please solve this issue

**Comment by OIVAS7572** [comment]
@CGP-Lichess 
I need logs from heroku.

**Comment by vibranium21** [comment]
For me the stack:set container -a appname step isn’t working

**Comment by OIVAS7572** [comment]
Appname means that is your heroku app's name

**Comment by OIVAS7572** [comment]
@CGP-Lichess 
Still it is not working send me what is output in cmd

**Comment by vibranium21** [comment]
Yes, I put the appname there but I doesn’t work do you think I can’t read the instructions?

**Comment by OIVAS7572** [comment]
What is it output? 
Comment here

**Comment by SathyaKarthik1212** [comment]
Hi now i helped CGPlichess

**Comment by vibranium21** [comment]
Heroku is not a batch file,a operable program or a command

**Comment by OIVAS7572** [comment]
I didn't say that is a batch file. What is the output showed in CMD when you run the command I give?

**Comment by vibranium21** [comment]
That I s the output

**Comment by vibranium21** [comment]
And I have downloaded and installed heroku cli multiple times

**Comment by OIVAS7572** [comment]
Oh Sorry, is that the output. I thought that is your comment.

I think there is a problem in Installation.
Sometimes it didn't added you Heroku to PATH

**Comment by TheYoBots** [comment]
From some operating systems, heroku doesn’t get added to path. You’ll have to manually add it to path @vibranium21
