### ISSUE TITLE
End of Free Heroku Dynos

### ISSUE THREAD

**Issue by OIVAS7572** [OIVAS7572/lichess-bot#162]
@TheYoBots 
I have received the mail from Heroku.
Please Go through this.
[Heroku Mail](https://hello.heroku.com/webmail/36622/1139539062/bc164f466baed9e2f7cbf6f176bb91ccf9e7840bc7f48ea29a73514324b542af)

**Comment by TheYoBots** [comment]
I know about that. What's the issue here though?

**Comment by SriMethan** [comment]
Finally, Heroku doesn't have any free plans, but I guess they have some eco plans or basic plans which charges only low cost to run the bot on Heroku,

If someone needs another free alternative of Heroku take a look at [cloudcommunity/Free-Hosting](https://github.com/cloudcommunity/Free-Hosting)

If someone prefers a paid alternative of Heroku take a look at [cloudcommunity/Cloud-Free-Tier-Comparison](https://github.com/cloudcommunity/Cloud-Free-Tier-Comparison)
