### ISSUE TITLE
Bot Not strong

### ISSUE THREAD

**Issue by SathyaKarthik1212** [OIVAS7572/lichess-bot#17]
Hi @OIVAS7572 , My bot is https://lichess.org/@/StockfishPro-BOT . I helped a person to make a bot strong with your code. It is https://lichess.org/@/adisidman . It played with my bot and it BOT Adisidman won! I used the Same code for both the Bots then why Bot Adisidman is Stronger Than my BOT StockfishPro-BOT

**Comment by OIVAS7572** [comment]
@SathyaKarthik1212 
Winning games between same powerfull bots are random. It will create somany draw games and some wins and loses. These are random.


If you feel this problem remake your bot like adisidman
