### ISSUE TITLE
Use Stockfish 14

### ISSUE THREAD

**Issue by SathyaKarthik1212** [OIVAS7572/lichess-bot#41]
Stockfish 14 is out! See https://stockfishchess.org/blog/2021/stockfish-14/ https://stockfishchess.org/download/

When will this be added in this repo??

**Comment by SathyaKarthik1212** [comment]
And which is stronger?? Sf13 or Sf14?

**Comment by OIVAS7572** [comment]
We will add Stockfish 14 soon and will delete Stockfish 13

**Comment by SathyaKarthik1212** [comment]
Ok Thanks. How to change it in MY repo? @OIVAS7572

**Comment by TheYoBots** [comment]
I have done it in my pull request #43

**Comment by SathyaKarthik1212** [comment]
Yobots did u add the file? and how to update from Stockfish 13 to Stockfish 14 in my repo?

**Comment by TheYoBots** [comment]
Update to this latest master build @SathyaKarthik1212

**Comment by SathyaKarthik1212** [comment]
How?

**Comment by TheYoBots** [comment]
I created a gist explaining how https://gist.github.com/TheYoBots/1185ab16b9807b9221eaa97d6af84a3c

**Comment by SathyaKarthik1212** [comment]
thanks

**Comment by SathyaKarthik1212** [comment]
Now i did it so will it now use SF14?

**Comment by SathyaKarthik1212** [comment]
Deployed as well @TheYoBots

**Comment by TheYoBots** [comment]
@SathyaKarthik1212 you haven’t updated your repository here https://github.com/SathyaKarthik1212/Bot-of-ChessGreatPlayer

**Comment by SathyaKarthik1212** [comment]
What i should update @TheYoBots

**Comment by TheYoBots** [comment]
Follow the steps here https://gist.github.com/TheYoBots/1185ab16b9807b9221eaa97d6af84a3c

**Comment by SathyaKarthik1212** [comment]
I did it already.

**Comment by TheYoBots** [comment]
It’s not done here https://github.com/SathyaKarthik1212/Bot-of-ChessGreatPlayer

**Comment by SathyaKarthik1212** [comment]
@TheYoBots this is the screenshot which i got after following the steps in ur gist. https://imgur.com/vonacfb

**Comment by TheYoBots** [comment]
Type this:
```
git checkout main
git fetch upstream master
git reset —hard upstream master
git push —force origin main
```

The error occurred because your branch name is different from the branch here https://github.com/OIVAS7572/lichess-bot

**Comment by SathyaKarthik1212** [comment]
Now i got https://i.imgur.com/fd1QlHe.png @TheYoBots
