### ISSUE TITLE
bot is not playing good moves only bad moves

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#45]
the bot is not playing the good moves it plays the bad and lost to 2300 player ;( how can i make the bot strong

**Comment by OIVAS7572** [comment]
@barca-cloud 
your fork is not updated
I suggest you to delete your repo and fork again from me and do setup from begin

**Comment by OIVAS7572** [comment]
or you can do Fetch upstream 
go to your [repo ](https://github.com/barca-cloud/barca-cloud-bot-repo)
there is a option Fetch upstream click that and click fetch merge
and deploy in heroku

**Comment by barca-cloud** [comment]
OK fine i fork you but how to delete repo

**Comment by barca-cloud** [comment]
fine i did it better now !

**Comment by barca-cloud** [comment]
can you see

**Comment by barca-cloud** [comment]
is it updated ??

**Comment by barca-cloud** [comment]
i did as you recomanded but when i use !name in it it say stockfish13

**Comment by TheYoBots** [comment]
> the bot is not playing the good moves it plays the bad and lost to 2300 player ;( how can i make the bot strong

That 2300 rated player seems to have been cheating in the games against you. I have reported him, I suggest you do so too @barca-cloud

**Comment by OIVAS7572** [comment]
> i did as you recomanded but when i use !name in it it say stockfish13

@barca-cloud 
you need to disconnect old repo in heroku and connect new repo then you need to deploy

**Comment by barca-cloud** [comment]
i did

**Comment by barca-cloud** [comment]
thank you! it working now

**Comment by barca-cloud** [comment]
also the bot iis taking it time very slowly how can i fix it ? it takes 20 secs to play first move ?

**Comment by TheYoBots** [comment]
Increase move overhead

**Comment by TheYoBots** [comment]
> i did as you recomanded but when i use !name in it it say stockfish13

@barca-cloud can you please send a game in which this happened?

**Comment by barca-cloud** [comment]
https://lichess.org/6PpBySyiLy4u

**Comment by barca-cloud** [comment]
but in this game it was stockfish 14 https://lichess.org/i8JVr35LszzO

**Comment by TheYoBots** [comment]
Ok then it has been fixed. 👍

I’ll close this now and push my pull request. Thanks.
