### ISSUE TITLE
We cant reach the app site 

### ISSUE THREAD

**Issue by stockfish13** [OIVAS7572/lichess-bot#50]
It gives error at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=enisbot.herokuapp.com request_id=1ad43f9c-190b-40ea-995e-bd46909a60a7 fwd="78.163.12.101" dyno= connect= service= status=503 bytes= protocol=http when i try to enter my bots apps web adress
O think you must add a web surface because it stops when i try to jeep open app

**Comment by OIVAS7572** [comment]
@stockfish13 
Our bot is not using a website. Our bot didn't need web process.
So you no need to open the site or app. Bot will work perfectly without that
