### ISSUE TITLE
Feature Request: Welcome Message

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#53]
tilte

**Comment by SathyaKarthik1212** [comment]
U mean like bot of @TheYoBots

**Comment by barca-cloud** [comment]
yea

**Comment by SathyaKarthik1212** [comment]
Ask him only

**Comment by OIVAS7572** [comment]
@barca-cloud 
our source code is from https://github.com/ShailChoksi/lichess-bot
If you need any imporvement ask  there

**Comment by TheYoBots** [comment]
I think the already existing conversation might be overwritten if a welcome message is added, so it might crash the bot. I’m currently not using this hence I am able to do it easily.

**Comment by barca-cloud** [comment]
i am closing this now.
