### ISSUE TITLE
Can't add any Engine

### ISSUE THREAD

**Issue by barca-cloud2010** [OIVAS7572/lichess-bot#62]
View my repository [here](https://github.com/barca-cloud2010/lichess-bot) for more details.

**Comment by TheYoBots** [comment]
1. Please don't put all CAPS.
2. Please explain your issue in detail with information such as what you did and after doing that what you expected to happen and what happened instead.

Thanks.

**Comment by barca-cloud2010** [comment]
i want to add an engine so that bot plays some variants but i could not see anywere to add engine.

**Comment by TheYoBots** [comment]
For variants use the `variants` branch or use this repository https://github.com/striker2211/lichess-bot

To add an engines, simply add it to the `.` directory of your repository.

**Comment by barca-cloud2010** [comment]
where is .

**Comment by TheYoBots** [comment]
All files are in the `.` directory.

**Comment by barca-cloud2010** [comment]
link. @TheYoBots

**Comment by TheYoBots** [comment]
Bruh... Wdym link?
