### ISSUE TITLE
welcome message from shals chosky

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#69]
@OIVAS7572 can we have this thing https://github.com/ShailChoksi/lichess-bot/pull/375/files

**Comment by OIVAS7572** [comment]
@barca-cloud  
I will commit when it is merged to ShailChoksi's repo.
If you want you can create a new branch with mannually added changes in your repo

**Comment by barca-cloud** [comment]
btw there is some of my repo which greeting have like this https://github.com/barca-cloud/lichess-bot-1/tree/bot-greeting so can i add heroku yml so that i can use that repo?

**Comment by OIVAS7572** [comment]
Don't need to make pr
we will do it.
