### ISSUE TITLE
bot is not playing well in 30 sec match

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#77]
see in this game the bot blundered many things but still i lost https://lichess.org/2uWYfVR3EcPD

**Comment by barca-cloud** [comment]
pls help @OIVAS7572

**Comment by OIVAS7572** [comment]
you won in that game check it

**Comment by OIVAS7572** [comment]
@barca-cloud

**Comment by barca-cloud** [comment]
i mean the non bot player

**Comment by TheYoBots** [comment]
If the non-bot player blundered, then why is that a bot issue.

**Comment by barca-cloud** [comment]
no the bot also blundered a lot @TheYoBots

**Comment by TheYoBots** [comment]
But the bot won.

**Comment by barca-cloud** [comment]
yes that bescause i blundered!

**Comment by barca-cloud** [comment]
i was winning
