### ISSUE TITLE
Update to Stockfish [latest dev] (Using version for modern CPUs)

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#78]
can it be added?

**Comment by OIVAS7572** [comment]
@OIVAS7572
yes it is possible.
we are creating documentation about changing engine

**Comment by barca-cloud** [comment]
thank you!

**Comment by barca-cloud** [comment]
@TheYoBots what do you say?

**Comment by TheYoBots** [comment]
What is ppt?

**Comment by OIVAS7572** [comment]
@barca-cloud 
yes, what is ppt?

**Comment by barca-cloud** [comment]
oh my typo LOL  popcnt THAT I MEANT

**Comment by TheYoBots** [comment]
I’ve updated it and added necessary documentation in this commit https://github.com/OIVAS7572/lichess-bot/commit/db772e1c3cf1db1dac757e563b99fcee45a22021

**Comment by barca-cloud** [comment]
@TheYoBots pls change back to stockfish 14 dev it better than regular sf14

**Comment by barca-cloud** [comment]
oh i got it no need for that
