### ISSUE TITLE
Removal of Excess of Branches to this repo

### ISSUE THREAD

**Issue by TheYoBots** [OIVAS7572/lichess-bot#8]
This repo has many extra branches that are of no use and no connection to the master repo. Please do delete all the branches that are not being used in this repo.

**Comment by OIVAS7572** [comment]
I don't Know how this come here.
Anyway how to delete branch. I don't know that.please help me
Thanks

**Comment by TheYoBots** [comment]
Click on main in your repo, then click on view all branches and then click on the delete button :)

**Comment by OIVAS7572** [comment]
I closed

**Comment by OIVAS7572** [comment]
I didn't see that option in mobile phone

**Comment by OIVAS7572** [comment]
Thankyou very much

**Comment by TheYoBots** [comment]
Also what is https://github.com/OIVAS7572/lichess-bot/commit/973802d1939002aefff6c4cdb9adfad31aff64ee and https://github.com/OIVAS7572/lichess-bot/commit/e002c287550b9ac0fe902bc39cd07124d9fcc63e for?

**Comment by OIVAS7572** [comment]
I am going to close this

**Comment by TheYoBots** [comment]
@OIVAS7572 https://github.com/OIVAS7572/lichess-bot/issues/8#issuecomment-792271711 ?

**Comment by OIVAS7572** [comment]
is that is bad to my repo

**Comment by OIVAS7572** [comment]
I see those options in my repo settings and I make that enable
i there any problem
thanks

**Comment by TheYoBots** [comment]
@OIVAS7572 nothing bad, just not meant for this repository.

**Comment by OIVAS7572** [comment]
That is not setted up. That is the default document.I didn't got time to setup.I don't much about how to setup. Anyway I will do anything to that.thank you

**Comment by TheYoBots** [comment]
Oh ok, but it wouldn’t make sense for this repo. But if you want add it.
