### ISSUE TITLE
@ovaisis why did you change the engine

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#81]
@OIVAS7572 why did you it was working well for me

**Comment by TheYoBots** [comment]
Idk, you can use the previous commit if you want

**Comment by OIVAS7572** [comment]
@barca-cloud 
I created new branch for stockfish dev. If you want you can use it

**Comment by barca-cloud** [comment]
well i changed in dockerfle and it now working well
