### ISSUE TITLE
A WEIRD BUG

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#85]
=== Fetching app code
=== Building worker (Dockerfile)
Sending build context to Docker daemon  942.6kBStep 1/13 : FROM debian:stable-slim
stable-slim: Pulling from library/debian
fc491617b0f1: Pulling fs layer
fc491617b0f1: Verifying Checksum
fc491617b0f1: Download complete
fc491617b0f1: Pull complete
Digest: sha256:a85c2c0e634946e92a6f4a9a4f6ce5f19ce7c11885bc198f04ab3ae8dacbaffa
Status: Downloaded newer image for debian:stable-slim
 ---> 6a055693f486
Step 2/13 : MAINTAINER OIVAS7572
 ---> Running in e379ec16cc29
Removing intermediate container e379ec16cc29
 ---> 4aeb704b0506
Step 3/13 : RUN echo OIVAS7572
 ---> Running in accc95c52018
OIVAS7572
Removing intermediate container accc95c52018
 ---> 1b861bfa3bff
Step 4/13 : CMD echo OIVAS7572
 ---> Running in 9bcae103d004
Removing intermediate container 9bcae103d004
 ---> 55469674b8cd
Step 5/13 : COPY . .
 ---> b8e1d9466cc8
Step 6/13 : RUN apt-get update && apt-get install -y wget python3 python3-pip p7zip-full
 ---> Running in 654d6cb0d974
Ign:1 http://security.debian.org/debian-security stable/updates InRelease
Err:2 http://security.debian.org/debian-security stable/updates Release
  404  Not Found [IP: 151.101.194.132 80]
Get:3 http://deb.debian.org/debian stable InRelease [113 kB]
Get:4 http://deb.debian.org/debian stable-updates InRelease [36.8 kB]
Get:5 http://deb.debian.org/debian stable/main amd64 Packages [8178 kB]
Reading package lists...
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
The command '/bin/sh -c apt-get update && apt-get install -y wget python3 python3-pip p7zip-full' returned a non-zero code: 100 not deploying why?

**Comment by barca-cloud** [comment]
== Fetching app code
=== Building worker (Dockerfile)
Sending build context to Docker daemon  942.6kBStep 1/13 : FROM debian:stable-slim
stable-slim: Pulling from library/debian
fc491617b0f1: Pulling fs layer
fc491617b0f1: Verifying Checksum
fc491617b0f1: Download complete
fc491617b0f1: Pull complete
Digest: sha256:a85c2c0e634946e92a6f4a9a4f6ce5f19ce7c11885bc198f04ab3ae8dacbaffa
Status: Downloaded newer image for debian:stable-slim
 ---> 6a055693f486
Step 2/13 : MAINTAINER OIVAS7572
 ---> Running in e1ae6b41d19e
Removing intermediate container e1ae6b41d19e
 ---> 9d18f45e916e
Step 3/13 : RUN echo OIVAS7572
 ---> Running in fb105d05bfc5
OIVAS7572
Removing intermediate container fb105d05bfc5
 ---> 2da12f58ea75
Step 4/13 : CMD echo OIVAS7572
 ---> Running in e943557ca8c9
Removing intermediate container e943557ca8c9
 ---> ceadf6f0e86d
Step 5/13 : COPY . .
 ---> 5be5c27695dc
Step 6/13 : RUN apt-get update && apt-get install -y wget python3 python3-pip p7zip-full
 ---> Running in 1dc7381234aa
Ign:1 http://security.debian.org/debian-security stable/updates InRelease
Err:2 http://security.debian.org/debian-security stable/updates Release
  404  Not Found [IP: 151.101.130.132 80]
Get:3 http://deb.debian.org/debian stable InRelease [113 kB]
Get:4 http://deb.debian.org/debian stable-updates InRelease [36.8 kB]
Get:5 http://deb.debian.org/debian stable/main amd64 Packages [8178 kB]
Reading package lists...
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
The command '/bin/sh -c apt-get update && apt-get install -y wget python3 python3-pip p7zip-full' returned a non-zero code: 100

**Comment by barca-cloud** [comment]
pls help

**Comment by OIVAS7572** [comment]
@barca-cloud
Some error docker-image

**Comment by OIVAS7572** [comment]
I don't have pc now so I can't troubleshoot

**Comment by OIVAS7572** [comment]
Please tryafter sometime

**Comment by barca-cloud** [comment]
@TheYoBots can you fix it (sorry for ping)

**Comment by OIVAS7572** [comment]
Change first line of dockerfile to `FROM ubuntu:latest`
and try it.

**Comment by barca-cloud** [comment]
ok

**Comment by barca-cloud** [comment]
@OIVAS7572 thx it working now

**Comment by barca-cloud** [comment]
@OIVAS7572 closing now juts one thing change it in ur docker file pls so it wont get the bug again
