### ISSUE TITLE
add this opening book also upgrade stockfish with  nnue

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#87]
https://workupload.com/file/E5atKBeeYW8 add this book also pls upgrade the stockfish there is a new version of stockfish also pls  add nnue thing

**Comment by barca-cloud** [comment]
@OIVAS7572 ??

**Comment by OIVAS7572** [comment]
What you mean by adding nnue

**Comment by barca-cloud** [comment]
it a default make it permanent

**Comment by OIVAS7572** [comment]
What didn't understand?

**Comment by TheYoBots** [comment]
1. NNUE is used already.
2. If you want that opening book add it yourself.

**Comment by barca-cloud** [comment]
how cvan i add it @TheYoBots

**Comment by TheYoBots** [comment]
Download it and add it
