### ISSUE TITLE
variants bot didn't make a move

### ISSUE THREAD

**Issue by RishabBindal** [OIVAS7572/lichess-bot#88]
https://github.com/OIVAS7572/lichess-bot/tree/variants I tried with my bot but he is 24/7 online but when I start a game of variants my bot is not moving a single move

**Comment by TheYoBots** [comment]
Please send the error logs when reporting an issue.

**Comment by RishabBindal** [comment]
https://lichess.org/YapPw1Bx in this game if you see match was abort because my bot didn't play any move

**Comment by barca-cloud** [comment]
semd heroku errors not the games bruh!!1

**Comment by RishabBindal** [comment]
no error on Heroku was there

**Comment by barca-cloud** [comment]
@RishabBindal pls close if it done odnt close reopen juts close it no need to reopen

**Comment by RishabBindal** [comment]
my bot is not playing variants

**Comment by RishabBindal** [comment]
if you challenge https://lichess.org/@/Rishab1_Variants_Bot then it will not play any move

**Comment by barca-cloud** [comment]
bruh try to play a antichess game then that momment give heroku logs also dont abort it 👍
