### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#89]
My BOT lost 116 points due to 30 secs match with human. Not joking, please help. It is playing so bad at 30 secs match.

**Comment by barca-cloud** [comment]
@OIVAS7572 pls help as @barca-cloud @TheYoBots wont help me pls

**Comment by OIVAS7572** [comment]
@barca-cloud 
Which game

**Comment by TheYoBots** [comment]
> My BOT lost 116 points due to 30 secs match with human. Not joking, please help. It is playing so bad at 30 secs match.

Please no all CAPS.



> @OIVAS7572 pls help as @TheYoBots wont help me pls

Please no ping.

Please provide more info. Send the game link, the error faced during the game, etc.

**Comment by barca-cloud** [comment]
well i got solution it bescause of the book thanks for it i got solution
