### ISSUE TITLE
use latest dev version

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#94]
there is a new version of dev here [here](https://abrok.eu/stockfish/)

**Comment by TheYoBots** [comment]
If you want to use it, then… use it! 

Read instructions [here](https://github.com/OIVAS7572/lichess-bot#how-to-change-the-engine-used).

**Comment by OIVAS7572** [comment]
If you want to use the SFdev latest version. deploy your SFdev branch in Heroku to update the engine.

**Comment by OIVAS7572** [comment]
@barca-cloud

**Comment by barca-cloud** [comment]
yea i saw it now anyway i will do it main
